
common_abbreviations= {
  "abbr": "abbreviation",
  "AWOL": "absent without leave",
  "Acad": "Academy",
  "alt": "altitude",
  "AM": "amplitude modulation",
  "AD": "anno Domini",
  "AM": "ante meridiem (before noon)",
  "apt": "apartment",
  "Assn": "Association",
  "Aug": "August",
  "Ave": "Avenue",
  "BA": "Bachelor of Arts",
  "BS": "Bachelor of Science",
  "BC": "Before Christ",
  "Blvd": "Boulevard",
  "Capt": "Captain",
  "C": "Celsius, Centigrade",
  "ctr": "center",
  "cm": "centimeter",
  "cent": "century",
  "Col": "Colonel",
  "Cpl": "Corporal",
  "Corp": "Corporation",
  "Ct": "Court",
  "cu": "cubic",
  "dept": "department",
  "DC": "District of Columbia",
  "Dr": "Doctor",
  "div": "division",
  "Dr": "Drive",
  "E": "east",
  "ed": "edition",
  "etc": "et cetera (and so on)",
  "F": "Fahrenheit",
  "Feb": "February",
  "ft": "foot",
  "Ft": "Fort",
  "FM": "frequency modulation",
  "gal": "gallon",
  "Gen": "General",
  "Gov": "Governor",
  "GMT": "Greenwich Mean Time",
  "hwy": "highway",
  "hr": "hour",
  "ie": "id est (that is)",
  "in": "inch",
  "inc": "incorporated",
  "Jan": "January",
  "Jr": "Junior",
  "K": "Kelvin",
  "kg": "kilogram",
  "km": "kilometer",
  "Lk": "Lake",
  "Ln": "Lane",
  "lib": "library",
  "lat": "latitude",
  "Lt": "Lieutenant",
  "Ltd": "Limited",
  "long": "longitude",
  "m": "meter",
  "min": "minute",
  "MD": "Medical Doctor",
  "MD": "Medicinae Doctor",
  "mi": "mile",
  "mph": "miles per hour",
  "mg": "milligram",
  "mm": "millimeter",
  "Mr": "Mister",
  "Msgr": "Monsignor",
  "mo": "month",
  "mt": "mountain",
  "mus": "museum",
  "N": "north",
  "Nov": "November",
  "no": "number",
  "Oct": "October",
  "oz": "ounce",
  "p": "page",
  "pt": "pint",
  "pl": "plural",
  "pop": "population",
  "PM": "post meridiem (after noon)",
  "Prof": "Professor",
  "qt": "quart",
  "Rd": "Road",
  "RN": "Registered Nurse",
  "rpm": "revolutions per minute",
  "sec": "second",
  "Sept": "September",
  "Sgt": "Sergeant",
  "Sr": "Sister",
  "S": "south",
  "sq": "square",
  "Sta": "Station",
  "St": "Street",
  "ste": "suite",
  "Sun": "Sunday",
  "Ter": "Terrace",
  "Tpk": "Turnpike",
  "Univ": "University",
  "USA": "United States of America",
  "vol": "volume",
  "wt": "weight",
  "W": "west",
  "AA": "Armed Forces Americas",
  "AE": "Armed Forces Europe",
  "AK": "Alaska",
  "AL": "Alabama",
  "AP": "Armed Forces Pacific",
  "AR": "Arkansas",
  "AS": "American Somoa",
  "AZ": "Arizona",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DC": "District of Columbia",
  "DE": "Delaware",
  "FL": "Florida",
  "FM": "Federated States of Micronesia",
  "GA": "Georgia",
  "GU": "Guam",
  "HI": "Hawaii",
  "IA": "Iowa",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "MA": "Massachusetts",
  "MD": "Maryland",
  "ME": "Maine",
  "MH": "Marshall Islands",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MO": "Missouri",
  "MP": "Northern Mariana Islands",
  "MS": "Mississippi",
  "MT": "Montana",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "NE": "Nebraska",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NV": "Nevada",
  "NY": "New York",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "PR": "Puerto Rico",
  "PW": "Palau",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VA": "Virginia",
  "VI": "Virgin Islands",
  "VT": "Vermont",
  "WA": "Washington",
  "WI": "Wisconsin",
  "WV": "West Virginia",
  "WY": "Wyoming",
  "ALY": "ALLEY",
  "ANX": "ANNEX",
  "APT": "APARTMENT",
  "ARC": "ARCADE",
  "AVE": "AVENUE",
  "BSMT": "BASEMENT",
  "BYU": "BAYOU",
  "BCH": "BEACH",
  "BND": "BEND",
  "BLF": "BLUFF",
  "BTM": "BOTTOM",
  "BLVD": "BOULEVARD",
  "BR": "BRANCH",
  "BRG": "BRIDGE",
  "BRK": "BROOK",
  "BLDG": "BUILDING",
  "BG": "BURG",
  "BYP": "BYPASS",
  "CP": "CAMP",
  "CYN": "CANYON",
  "CPE": "CAPE",
  "CSWY": "CAUSEWAY",
  "CTR": "CENTER",
  "CIR": "CIRCLE",
  "CLFS": "CLIFF",
  "CLFS": "CLIFFS",
  "CLB": "CLUB",
  "COR": "CORNER",
  "CORS": "CORNERS",
  "CRSE": "COURSE",
  "CT": "COURT",
  "CTS": "COURTS",
  "CV": "COVE",
  "CRK": "CREEK",
  "CRES": "CRESCENT",
  "XING": "CROSSING",
  "DL": "DALE",
  "DM": "DAM",
  "DEPT": "DEPARTMENT",
  "DV": "DIVIDE",
  "DR": "DRIVE",
  "EST": "ESTATE",
  "EXPY": "EXPRESSWAY",
  "EXT": "EXTENSION",
  "FLS": "FALLS",
  "FRY": "FERRY",
  "FLD": "FIELD",
  "FLDS": "FIELDS",
  "FLT": "FLAT",
  "FL": "FLOOR",
  "FRD": "FORD",
  "FRST": "FOREST",
  "FRG": "FORGE",
  "FRK": "FORK",
  "FRKS": "FORKS",
  "FT": "FORT",
  "FWY": "FREEWAY",
  "FRNT": "FRONT",
  "GDNS": "GARDEN",
  "GDNS": "GARDENS",
  "GTWY": "GATEWAY",
  "GLN": "GLEN",
  "GRN": "GREEN",
  "GRV": "GROVE",
  "HNGR": "HANGER",
  "HBR": "HARBOR",
  "HVN": "HAVEN",
  "HTS": "HEIGHTS",
  "HWY": "HIGHWAY",
  "HL": "HILL",
  "HLS": "HILLS",
  "HOLW": "HOLLOW",
  "INLT": "INLET",
  "IS": "ISLAND",
  "ISS": "ISLANDS",
  "JCT": "JUNCTION",
  "KY": "KEY",
  "KNLS": "KNOLL",
  "KNLS": "KNOLLS",
  "LK": "LAKE",
  "LKS": "LAKES",
  "LNDG": "LANDING",
  "LN": "LANE",
  "LGT": "LIGHT",
  "LF": "LOAF",
  "LBBY": "LOBBY",
  "LCKS": "LOCK",
  "LCKS": "LOCKS",
  "LDG": "LODGE",
  "LOWR": "LOWER",
  "MNR": "MANOR",
  "MDWS": "MEADOW",
  "MDWS": "MEADOWS",
  "ML": "MILL",
  "MLS": "MILLS",
  "MSN": "MISSION",
  "MT": "MOUNT",
  "MTN": "MOUNTAIN",
  "NCK": "NECK",
  "OFC": "OFFICE",
  "ORCH": "ORCHARD",
  "PKWY": "PARKWAY",
  "PH": "PENTHOUSE",
  "PNES": "PINE",
  "PNES": "PINES",
  "PL": "PLACE",
  "PLN": "PLAIN",
  "PLNS": "PLAINS",
  "PLZ": "PLAZA",
  "PT": "POINT",
  "PRT": "PORT",
  "PR": "PRAIRIE",
  "RADL": "RADIAL",
  "RNCH": "RANCH",
  "RPDS": "RAPID",
  "RPDS": "RAPIDS",
  "RST": "REST",
  "RDG": "RIDGE",
  "RIV": "RIVER",
  "RD": "ROAD",
  "RM": "ROOM",
  "SHL": "SHOAL",
  "SHLS": "SHOALS",
  "SHR": "SHORE",
  "SHRS": "SHORES",
  "SPC": "SPACE",
  "SPG": "SPRING",
  "SPGS": "SPRINGS",
  "SQ": "SQUARE",
  "STA": "STATION",
  "STRA": "STRAVENUE",
  "STRM": "STREAM",
  "ST": "STREET",
  "STE": "SUITE",
  "SMT": "SUMMIT",
  "TER": "TERRACE",
  "TRCE": "TRACE",
  "TRAK": "TRACK",
  "TRFY": "TRAFFICWAY",
  "TRL": "TRAIL",
  "TRLR": "TRAILER",
  "TUNL": "TUNNEL",
  "TPKE": "TURNPIKE",
  "UN": "UNION",
  "UPPR": "UPPER",
  "VLY": "VALLEY",
  "VIA": "VIADUCT",
  "VW": "VIEW",
  "VLG": "VILLAGE",
  "VL": "VILLE",
  "VIS": "VISTA",
  "WAY": "WAY",
  "WLS": "WELL",
  "WLS": "WELLS"
}
